/* Generated by Pyrex 0.9.3 on Sat Sep 17 00:53:28 2005 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "numarray/libnumarray.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

static char __pyx_mdoc[] = "\nA Pyrex extension module for numarray.  Currently this extension\nmodule allows us to massage a 2D numarray array into a form usable as\na `vtkIdTypeArray`.  This is then used to set the cells of a\n`vtkCellArray` instance.\n";

/* Declarations from array_ext_na */

static PyTypeObject *__pyx_ptype_12array_ext_na__numarray = 0;
static PyObject *__pyx_k3;
static PyObject *(__pyx_f_12array_ext_na_c_set_id_type_array(PyArrayObject *,PyArrayObject *)); /*proto*/

/* Implementation of array_ext_na */


static PyObject *__pyx_n_numarray;
static PyObject *__pyx_n_empty_array;
static PyObject *__pyx_n_set_id_type_array;
static PyObject *__pyx_n_d;

static PyObject *__pyx_f_12array_ext_na_c_set_id_type_array(PyArrayObject *__pyx_v_id_array,PyArrayObject *__pyx_v_out_array) {
  int __pyx_v_cell_length;
  int __pyx_v_dim0;
  int (*__pyx_v_id_data);
  int (*__pyx_v_out_data);
  int __pyx_v_stride0;
  int __pyx_v_stride1;
  int __pyx_v_i;
  int __pyx_v_j;
  int __pyx_v_in_idx;
  int __pyx_v_out_idx;
  PyObject *__pyx_r;
  Py_INCREF(__pyx_v_id_array);
  Py_INCREF(__pyx_v_out_array);

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":48 */
  __pyx_v_cell_length = (__pyx_v_id_array->dimensions[1]);

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":49 */
  __pyx_v_dim0 = (__pyx_v_id_array->dimensions[0]);

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":50 */
  __pyx_v_id_data = ((int (*))__pyx_v_id_array->data);

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":51 */
  __pyx_v_out_data = ((int (*))__pyx_v_out_array->data);

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":52 */
  __pyx_v_stride0 = ((__pyx_v_id_array->strides[0]) / (sizeof(int )));

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":53 */
  __pyx_v_stride1 = ((__pyx_v_id_array->strides[1]) / (sizeof(int )));

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":56 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_dim0; ++__pyx_v_i) {

    /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":57 */
    __pyx_v_in_idx = (__pyx_v_i * __pyx_v_stride0);

    /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":58 */
    __pyx_v_out_idx = ((__pyx_v_i * __pyx_v_cell_length) + __pyx_v_i);

    /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":59 */
    (__pyx_v_out_data[__pyx_v_out_idx]) = __pyx_v_cell_length;

    /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":60 */
    for (__pyx_v_j = 0; __pyx_v_j < __pyx_v_cell_length; ++__pyx_v_j) {

      /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":61 */
      (__pyx_v_out_data[((__pyx_v_out_idx + __pyx_v_j) + 1)]) = (__pyx_v_id_data[(__pyx_v_in_idx + (__pyx_v_j * __pyx_v_stride1))]);
      __pyx_L4:;
    }
    __pyx_L5:;
    __pyx_L2:;
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("array_ext_na.c_set_id_type_array");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_id_array);
  Py_DECREF(__pyx_v_out_array);
  return __pyx_r;
}

static PyObject *__pyx_n_array;
static PyObject *__pyx_n_shape;
static PyObject *__pyx_n_type;


static PyObject *__pyx_f_12array_ext_na_empty_array(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12array_ext_na_empty_array[] = "A simple wrapper function along the lines of what is done for\n    older Numeric versions that returns an uninitialized numarray\n    array.";
static PyObject *__pyx_f_12array_ext_na_empty_array(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_dims = 0;
  PyObject *__pyx_v_typecode = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"dims","typecode",0};
  __pyx_v_typecode = __pyx_k3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_dims, &__pyx_v_typecode)) return 0;
  Py_INCREF(__pyx_v_dims);
  Py_INCREF(__pyx_v_typecode);

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":72 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numarray); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_array); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_3 = PyDict_New(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_3, __pyx_n_shape, __pyx_v_dims) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_3, __pyx_n_type, __pyx_v_typecode) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_4 = PyEval_CallObjectWithKeywords(__pyx_2, __pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("array_ext_na.empty_array");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_dims);
  Py_DECREF(__pyx_v_typecode);
  return __pyx_r;
}

static PyObject *__pyx_n_typecode;
static PyObject *__pyx_n_l;
static PyObject *__pyx_n_iscontiguous;
static PyObject *__pyx_n_len;
static PyObject *__pyx_n_size;

static PyObject *__pyx_k7p;
static PyObject *__pyx_k9p;
static PyObject *__pyx_k10p;
static PyObject *__pyx_k11p;
static PyObject *__pyx_k12p;

static char (__pyx_k7[]) = "id_array must have a typecode of 'l'.";
static char (__pyx_k9[]) = "out_array must have a typecode of 'l'.";
static char (__pyx_k10[]) = "out_array must be contiguous.";
static char (__pyx_k11[]) = "id_array must be a two dimensional array.";
static char (__pyx_k12[]) = "out_array size is incorrect, expected: %s, given: %s";

static PyObject *__pyx_f_12array_ext_na_set_id_type_array(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_12array_ext_na_set_id_type_array[] = "Given a 2D Int array (`id_array`), and a contiguous 1D numarray\n    array (`out_array`) having the correct size, this function sets\n    the data from `id_array` into `out_array` so that it can be used\n    in place of a `vtkIdTypeArray` in order to set the cells of a\n    `vtkCellArray`.\n\n    Note that if `shape = id_array.shape` then `size(out_array) ==\n    shape[0]*(shape[1] + 1)` should be true.  If not you\'ll get an\n    `AssertionError`.\n\n    `id_array` need not be contiguous but `out_array` must be.\n    ";
static PyObject *__pyx_f_12array_ext_na_set_id_type_array(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_id_array = 0;
  PyObject *__pyx_v_out_array = 0;
  PyObject *__pyx_v_shp;
  PyObject *__pyx_v_sz;
  PyObject *__pyx_v_e_sz;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"id_array","out_array",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_id_array, &__pyx_v_out_array)) return 0;
  Py_INCREF(__pyx_v_id_array);
  Py_INCREF(__pyx_v_out_array);
  __pyx_v_shp = Py_None; Py_INCREF(__pyx_v_shp);
  __pyx_v_sz = Py_None; Py_INCREF(__pyx_v_sz);
  __pyx_v_e_sz = Py_None; Py_INCREF(__pyx_v_e_sz);

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":88 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_id_array, __pyx_n_typecode); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_Cmp(__pyx_3, __pyx_n_l, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  __pyx_4 = __pyx_4 == 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (!__pyx_4) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_k7p);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  }

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":91 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_out_array, __pyx_n_typecode); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_Cmp(__pyx_3, __pyx_n_l, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_4 = __pyx_4 == 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (!__pyx_4) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_k9p);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  }

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":94 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_out_array, __pyx_n_iscontiguous); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_3, __pyx_1, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_4 = __pyx_4 == 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__pyx_4) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_k10p);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  }

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":97 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_id_array, __pyx_n_shape); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(__pyx_v_shp);
  __pyx_v_shp = __pyx_2;
  __pyx_2 = 0;

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":98 */
  __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  Py_INCREF(__pyx_v_shp);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_shp);
  __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyInt_FromLong(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_2, __pyx_3, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_4 = __pyx_4 == 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (!__pyx_4) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_k11p);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  }

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":100 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_numarray); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_size); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_INCREF(__pyx_v_out_array);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_out_array);
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_sz);
  __pyx_v_sz = __pyx_1;
  __pyx_1 = 0;

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":101 */
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_v_shp, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_2 = PyObject_GetItem(__pyx_v_shp, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_5 = PyNumber_Add(__pyx_2, __pyx_1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_2 = PyNumber_Multiply(__pyx_3, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_v_e_sz);
  __pyx_v_e_sz = __pyx_2;
  __pyx_2 = 0;

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":102 */
  if (PyObject_Cmp(__pyx_v_sz, __pyx_v_e_sz, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  __pyx_4 = __pyx_4 == 0;
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  Py_INCREF(__pyx_v_e_sz);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_e_sz);
  Py_INCREF(__pyx_v_sz);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_sz);
  __pyx_3 = PyNumber_Remainder(__pyx_k12p, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (!__pyx_4) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_3);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  }
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":105 */
  if (!__Pyx_TypeTest(__pyx_v_id_array, __pyx_ptype_12array_ext_na__numarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  if (!__Pyx_TypeTest(__pyx_v_out_array, __pyx_ptype_12array_ext_na__numarray)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  __pyx_5 = __pyx_f_12array_ext_na_c_set_id_type_array(((PyArrayObject *)__pyx_v_id_array),((PyArrayObject *)__pyx_v_out_array)); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("array_ext_na.set_id_type_array");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_shp);
  Py_DECREF(__pyx_v_sz);
  Py_DECREF(__pyx_v_e_sz);
  Py_DECREF(__pyx_v_id_array);
  Py_DECREF(__pyx_v_out_array);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_array, "array"},
  {&__pyx_n_d, "d"},
  {&__pyx_n_empty_array, "empty_array"},
  {&__pyx_n_iscontiguous, "iscontiguous"},
  {&__pyx_n_l, "l"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_numarray, "numarray"},
  {&__pyx_n_set_id_type_array, "set_id_type_array"},
  {&__pyx_n_shape, "shape"},
  {&__pyx_n_size, "size"},
  {&__pyx_n_type, "type"},
  {&__pyx_n_typecode, "typecode"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k9p, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k10p, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k11p, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_k12p, __pyx_k12, sizeof(__pyx_k12)},
  {0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"empty_array", (PyCFunction)__pyx_f_12array_ext_na_empty_array, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12array_ext_na_empty_array},
  {"set_id_type_array", (PyCFunction)__pyx_f_12array_ext_na_set_id_type_array, METH_VARARGS|METH_KEYWORDS, __pyx_doc_12array_ext_na_set_id_type_array},
  {0, 0, 0, 0}
};

PyMODINIT_FUNC initarray_ext_na(void); /*proto*/
PyMODINIT_FUNC initarray_ext_na(void) {
  PyObject *__pyx_1 = 0;
  __pyx_m = Py_InitModule4("array_ext_na", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_ptype_12array_ext_na__numarray = __Pyx_ImportType("numarray._numarray", "_numarray", sizeof(PyArrayObject)); if (!__pyx_ptype_12array_ext_na__numarray) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":12 */
  __pyx_1 = __Pyx_Import(__pyx_n_numarray, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_numarray, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":68 */
  Py_INCREF(__pyx_n_d);
  __pyx_k3 = __pyx_n_d;

  /* "/skratch/prabhu/svn/enthought/src/lib/enthought/tvtk/src/array_ext_na.pyx":75 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("array_ext_na");
}

static char *__pyx_filenames[] = {
  "array_ext_na.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module_name = 0;
    PyObject *py_class_name = 0;
    PyObject *py_name_list = 0;
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module_name = PyString_FromString(module_name);
    if (!py_module_name)
        goto bad;
    py_class_name = PyString_FromString(class_name);
    if (!py_class_name)
        goto bad;
    py_name_list = PyList_New(1);
    if (!py_name_list)
        goto bad;
    Py_INCREF(py_class_name);
    if (PyList_SetItem(py_name_list, 0, py_class_name) < 0)
        goto bad;
    py_module = __Pyx_Import(py_module_name, py_name_list);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttr(py_module, py_class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    goto done;
bad:
    Py_XDECREF(result);
    result = 0;
done:
    Py_XDECREF(py_module_name);
    Py_XDECREF(py_class_name);
    Py_XDECREF(py_name_list);
    return (PyTypeObject *)result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
