{ 'array': array([ (5.552, 1.942, 1.761, 2.6, 6.8),
                   (5.963, 1.885, 1.775, 2.7, 6.9),
                   (6.135, 1.791, 1.792, 2.5, 6.6),
                   (6.313, 1.774, 1.884, 2.6, 6.6),
                   (6.713, 1.762, 1.943, 2.5, 6.7)],
                 dtype=[('Column 1', float),
                        ('Column 2', float),
                        ('Column 3', float),
                        ('Column 4', float),
                        ('Column 5', float)]),

  'kwds': { 'comments': '#',
            'delimiter': None,
            'dtype': { 'formats': ( float,
                                    float,
                                    float,
                                    float,
                                    float),
                       'names': ( 'Column 1',
                                  'Column 2',
                                  'Column 3',
                                  'Column 4',
                                  'Column 5')},
            'skiprows': 0
            }
  }
